### ISSUE TITLE
Add Mavlink:jar as a new step to gradle build

### ISSUE THREAD

**Issue by Srwoerner** [kellyschrock/DroneKit-Android#5]
We ran into an issue where different branches, `sui_custom` and `solex_custom` in this case, were using different versions of Mavlink generated code. Because running `ClientLib:assembleRelease` does not rebuild the `Mavlink.jar` dependency its possible to build a somewhat working `.aar` of Drone-kit with the wrong `Mavlink.jar` which will fails silently in and leads to unexpected behaviors; like being able to connect to a vehicle  with normal telemetry, but not being able to upload a mission.

We should add `Mavlink:jar` as a step in the build process to avoid further hair pulling

**Comment by kellyschrock** [comment]
Done
